### PR TITLE
Exit and enter XIP for erase and write

### LINKED ISSUE #25: Flash error using openocd
I am trying to flash a binary with the following layout:

```
MEMORY
{
  /* boot from Flash */
  rom (rx)  : ORIGIN = 0x10000000, LENGTH = 128K
  prog (rx) : ORIGIN = 0x10020000, LENGTH = 1920K
  ram (rwx) : ORIGIN = 0x20004000, LENGTH = 256K
}

MPU_MIN_ALIGN = 8K;
PAGE_SIZE = 4K;
```

When trying to flash, I get the following openocd output:

```
$ openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg 
Open On-Chip Debugger 0.10.0+dev-geb22ace-dirty (2021-02-23-15:05)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
adapter speed: 1000 kHz

Info : Hardware thread awareness created
Info : Hardware thread awareness created
Info : RP2040 Flash Bank Command
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : BCM2835 GPIO JTAG/SWD bitbang driver
Info : clock speed 1001 kHz
Info : SWD DPIDR 0x0bc12477
Info : SWD DLPIDR 0x00000001
Info : SWD DPIDR 0x0bc12477
Info : SWD DLPIDR 0x10000001
Info : rp2040.core0: hardware has 4 breakpoints, 2 watchpoints
Info : rp2040.core1: hardware has 4 breakpoints, 2 watchpoints
Info : starting gdb server for rp2040.core0 on 3333
Info : Listening on port 3333 for gdb connections
Info : accepting 'gdb' connection on tcp/3333
Info : RP2040 B0 Flash Probe: 2097152 bytes @10000000, in 512 sectors

Info : New GDB Connection: 1, Target rp2040.core0, state: halted
undefined debug reason 8 - target needs reset
target halted due to debug-request, current mode: Thread 
xPSR: 0xf1000000 pc: 0x000000ee msp: 0x20041f00
target halted due to debug-request, current mode: Thread 
xPSR: 0xf1000000 pc: 0x000000ee msp: 0x20041f00
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0000012a msp: 0x20041f00
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0000012a msp: 0x20041f00
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0000012a msp: 0x20041f00
target halted due to debug-request, current mode: Thread 
xPSR: 0xf1000000 pc: 0x000000ee msp: 0x20041f00
target halted due to debug-request, current mode: Thread 
xPSR: 0xf1000000 pc: 0x000000ee msp: 0x20041f00
Error: Whole bank access must start at beginning of bank.
Error: flash_erase returned -904
```

Flashing works fine if I remove the `prog` line from the layout file or put the address somewhere in RAM (> 0x2000000).

### PR DESCRIPTION
**Pull request by alexandruradovici**
This PR fixes #25 by exiting and entering XIP mode separately for erase and write.

This will allow writing discontinuous flash regions.

### CODE REVIEW

File: src/flash/nor/rp2040.c [hunk 1]
```diff
@@ -172,6 +172,23 @@ static int rp2040_flash_write(struct flash_bank *bank, const uint8_t *buffer, ui
...
 	}
 
+	// This is a good place to do this because flash erase always follows a reset init
+	LOG_DEBUG("Connecting internal flash");
+	err = rp2040_call_rom_func(bank->target, priv->stacktop, FUNC_CONNECT_INTERNAL_FLASH, NULL, 0);
+	if (err != ERROR_OK)
+	{
+		LOG_ERROR("RP2040 write: failed to connect internal flash");
+		return err;
+	}
```
Comment (alexandruradovici) [inline src/flash/nor/rp2040.c:182]: I am not sure if this is really necessary for write

Comment (lurch) [reply src/flash/nor/rp2040.c:182]: Yeah, _probably_ no need to connect flash inside write, as I guess there'll always be an erase (some time) before a write.
Probably also no need to enter XIP mode at the end of erase, because there'll always be a write (some time) after an erase?
:man_shrugging: (hopefully @kilograham will be able to confirm)

Comment (alexandruradovici) [reply src/flash/nor/rp2040.c:182]: Entering XPI mode is necessary as the sequence of commands that gdb issues when writing discontinuous flash regions is erase, erase, write, write.

This is why we submitted this PR.

Comment (lurch) [reply src/flash/nor/rp2040.c:182]: I could be wrong, but AIUI the code previously assumed that the sequence would always be: [erase, write, erase, write] and with erase exiting XIP (before doing the erase), and write entering XIP (after doing the write) this would lead to:
```
exit-XIP
do-erase  # flash not in XIP mode

do-write  # flash not in XIP mode
enter-XIP

exit-XIP
do-erase  # flash not in XIP mode

do-write  # flash not in XIP mode
enter-XIP
# flash in XIP mode, execution can continue
```

However as you've discovered the sequence can _actually_ be [erase, erase, write, write] which leads to the erroneous sequence:
```
exit-XIP
do-erase  # flash not in XIP mode

exit-XIP
do-erase  # flash not in XIP mode

do-write  # flash not in XIP mode
enter-XIP

do-write  # flash in XIP mode - ERROR!
enter-XIP
```
where the second do-write fails, because the flash is still in XIP mode.

This PR changes the sequence to:
```
exit-XIP
do-erase  # flash not in XIP mode
enter-XIP

exit-XIP
do-erase  # flash not in XIP mode
enter-XIP

exit-XIP
do-write  # flash not in XIP mode
enter-XIP

exit-XIP
do-write  # flash not in XIP mode
enter-XIP
# flash in XIP mode, execution can continue
```

What I was suggesting with my comment above was that it's probably not necessary for the erase command to enter XIP mode, which would then lead to this sequence of commands:
```
exit-XIP
do-erase  # flash not in XIP mode

exit-XIP
do-erase  # flash not in XIP mode

exit-XIP
do-write  # flash not in XIP mode
enter-XIP

exit-XIP
do-write  # flash not in XIP mode
enter-XIP
# flash in XIP mode, execution can continue
```

I hope that makes sense? (of course this assumes that you'd never get a [erase, erase, write, write, erase] sequence _without_ a write at the very end)

Comment (alexandruradovici) [reply src/flash/nor/rp2040.c:182]: If that works, yes. I'm not sure it works though, but I will test and get back to you.

Comment (kilograham) [reply src/flash/nor/rp2040.c:182]: > I hope that makes sense? (of course this assumes that you'd never get a [erase, erase, write, write, erase] sequence _without_ a write at the very end)

The point is you *don't want* to be making assumptions about the order of calls over which you have no control

File: src/flash/nor/rp2040.c [hunk 2]
```diff
@@ -172,6 +172,23 @@ static int rp2040_flash_write(struct flash_bank *bank, const uint8_t *buffer, ui
 		return ERROR_TARGET_UNALIGNED_ACCESS;
 	}
 
+	// This is a good place to do this because flash erase always follows a reset init
```
Comment (kilograham) [inline src/flash/nor/rp2040.c:175]: I would remove this comment which is misleading

**Review by kilograham — CHANGES_REQUESTED** [review]

File: src/flash/nor/rp2040.c (hunk 1 above)
Comment (lurch) [reply src/flash/nor/rp2040.c:182]: > The point is you don't want to be making assumptions about the order of calls over which you have no control

Fair enough - perhaps that means that we _do_ also want to connect-flash from inside the write function then?

Maybe it's worth factoring out a couple of small functions (one to connect-flash and exit-xip, and another to enter-xip) which could be called from both the write function and the erase function? :shrug:

File: src/flash/nor/rp2040.c (hunk 2 above)
Comment (alexandruradovici) [reply src/flash/nor/rp2040.c]: Done

File: src/flash/nor/rp2040.c (hunk 1 above)
Comment (alexandruradovici) [reply src/flash/nor/rp2040.c:181]: Something like:

```c
static int rp2040_flash_init(struct flash_bank *bank)
{
        struct rp2040_flash_bank *priv = bank->driver_priv;
        err = rp2040_call_rom_func(bank->target, priv->stacktop, FUNC_CONNECT_INTERNAL_FLASH, NULL, 0);
	if (err != ERROR_OK)
	{
		LOG_ERROR("RP2040 write: failed to connect internal flash");
		return err;
	}
        return err;
}

static int rp2040_flash_exit_xip(struct flash_bank *bank)
{
        struct rp2040_flash_bank *priv = bank->driver_priv;
        err = rp2040_call_rom_func(bank->target, priv->stacktop, FUNC_FLASH_EXIT_XIP, NULL, 0);
	if (err != ERROR_OK)
	{
		LOG_ERROR("RP2040 write: failed to exit flash XIP mode");
		return err;
	}
        return err;
}

static int rp2040_flash_enter_exip(struct flash_bank *bank)
{
        struct rp2040_flash_bank *priv = bank->driver_priv;
        err = rp2040_call_rom_func(bank->target, priv->stacktop, FUNC_FLASH_ENTER_CMD_XIP, NULL, 0);
	if (err != ERROR_OK)
	{
		LOG_ERROR("RP2040 write: failed enter flash XIP mode");
	}
        return err;
}
```

Comment (lurch) [reply src/flash/nor/rp2040.c:181]: Yeah but I was thinking you could combine your `rp2040_flash_init` and `rp2040_flash_exit_xip` functions into a single function, since they always get used together? :shrug:

Comment (alexandruradovici) [reply src/flash/nor/rp2040.c:181]: If this is OK with everyone, I'll add it to the code.

```c
static int rp2040_flash_exit_xip(struct flash_bank *bank)
{
        struct rp2040_flash_bank *priv = bank->driver_priv;
        err = rp2040_call_rom_func(bank->target, priv->stacktop, FUNC_CONNECT_INTERNAL_FLASH, NULL, 0);
	if (err != ERROR_OK)
	{
		LOG_ERROR("RP2040 write: failed to connect internal flash");
		return err;
	}
        err = rp2040_call_rom_func(bank->target, priv->stacktop, FUNC_FLASH_EXIT_XIP, NULL, 0);
	if (err != ERROR_OK)
	{
		LOG_ERROR("RP2040 write: failed to exit flash XIP mode");
		return err;
	}
        return err;
}

static int rp2040_flash_enter_exip(struct flash_bank *bank)
{
        struct rp2040_flash_bank *priv = bank->driver_priv;
        err = rp2040_call_rom_func(bank->target, priv->stacktop, FUNC_FLASH_ENTER_CMD_XIP, NULL, 0);
	if (err != ERROR_OK)
	{
		LOG_ERROR("RP2040 write: failed enter flash XIP mode");
	}
        return err;
}
```

Comment (lurch) [reply src/flash/nor/rp2040.c:181]: a) you probably want to change the error-strings to say something like "RP2040 exit_xip: ..." and "RP2040 enter_xip: ..." ? (and perhaps change "failed enter" to "failed to enter")
b) I think you want to add `int err = ERROR_OK;` near the top of each of those functions
c) `rp2040_flash_enter_exip` -> `rp2040_flash_enter_xip` ? :wink: 
d) it might be worth waiting for the go-ahead from @kilograham

Comment (alexandruradovici) [reply src/flash/nor/rp2040.c:181]: > a) you probably want to change the error-strings to say something like "RP2040 exit_xip: ..." and "RP2040 enter_xip: ..." ? (and perhaps change "failed enter" to "failed to enter")
Sure :)
> b) I think you want to add `int err = ERROR_OK;` near the top of each of those functions
I think we can add int `err = rp2040_call_rom_func ...`
> c) `rp2040_flash_enter_exip` -> `rp2040_flash_enter_xip` ? 😉
:)
> d) it might be worth waiting for the go-ahead from @kilograham

Comment (alexandruradovici) [reply src/flash/nor/rp2040.c]: Dome

File: src/flash/nor/rp2040.c [hunk 3]
```diff
@@ -172,16 +210,7 @@ static int rp2040_flash_write(struct flash_bank *bank, const uint8_t *buffer, ui
...
-		LOG_ERROR("RP2040 write: failed to connect internal flash");
-		return err;
-	}
-
-	LOG_DEBUG("Kicking flash out of XIP mode");
-	err = rp2040_call_rom_func(bank->target, priv->stacktop, FUNC_FLASH_EXIT_XIP, NULL, 0);
+	err = rp2040_flash_exit_xip (bank);
 	if (err != ERROR_OK)
 	{
 		LOG_ERROR("RP2040 write: failed to exit flash XIP mode");
```
Comment (lurch) [inline src/flash/nor/rp2040.c:216]: Probably not much point in doing `LOG_ERROR` in both `rp2040_flash_exit_xip` **and** `rp2040_flash_write` ?
I.e. this should probably be just:
```
	err = rp2040_flash_exit_xip(bank);
	if (err != ERROR_OK)
		return err;
```
:shrug: 
(also, please try to stick to the existing formatting-style of no space between `rp2040_flash_exit_xip` and `(bank)`)

File: src/flash/nor/rp2040.c [hunk 4]
```diff
@@ -156,6 +156,44 @@ struct rp2040_flash_bank {
...
+static int rp2040_flash_enter_xip(struct flash_bank *bank) 
+{
+	struct rp2040_flash_bank *priv = bank->driver_priv;
+	int err = ERROR_OK;
+
+	LOG_DEBUG("Configuring SSI for execute-in-place");
+	err = rp2040_call_rom_func(bank->target, priv->stacktop, FUNC_FLASH_ENTER_CMD_XIP, NULL, 0);
+	if (err != ERROR_OK)
+	{
+		LOG_ERROR("RP2040 enter xip: failed enter flash XIP mode");
```
Comment (lurch) [inline src/flash/nor/rp2040.c:192]: "failed to enter" ?

File: src/flash/nor/rp2040.c (hunk 3 above)
Comment (alexandruradovici) [reply src/flash/nor/rp2040.c:216]: Done

File: src/flash/nor/rp2040.c (hunk 4 above)
Comment (alexandruradovici) [reply src/flash/nor/rp2040.c]: Yep

**Comment by alexandruradovici** [comment]
Ping?

**Comment by alexandruradovici** [comment]
@kilograham Just a kind reminder about this PR, it is more or less a blocker for us when] using Tock. Is there anything that I can help with to get this merged?

**Comment by alexandruradovici** [comment]
Hi guys, we would really appreciate merging this. This is the only blocker that we have for merging the Pico into Tock.

@kilograham @Wren6991 is there anything that we can help you with to speed up the merge?

**Review by Wren6991 — COMMENTED** [review]
Thanks, the only issue I can see with the patch is that the cache flushed following a write, but not an erase. Coherency aside, the flush function also restores normal operation of the chip select pin (which is bitbanged during programming, to avoid chip select deassertion during USB interrupts). See here:
https://github.com/raspberrypi/pico-bootrom/blob/00a4a19114195e20fb817bdfbca1165e157eef37/bootrom/program_flash_generic.c#L432

So in the interest of not blocking you further, I'll amend this by pulling that code into `rp2040_flash_enter_xip()` and then merge this. Hope this is ok.

**Review by Wren6991 — APPROVED** [review]
I don't have commit access to your PR branch, so I will merge this as-is (it shouldn't cause any regression), and then apply the erase flush fix separately

**Comment by alexandruradovici** [comment]
Thank you for merging it.
